rules:
  # Secrets and credential patterns
  - id: local.secrets.generic
    languages: [generic]
    message: Possible secret/credential detected
    severity: ERROR
    paths:
      include: ["**"]
      exclude: ["**/.semgrep.yaml"]
    patterns:
      - pattern-either:
          - pattern: /AIza[0-9A-Za-z\-_]{35}/
          - pattern: /ghp_[0-9A-Za-z]{36}/
          - pattern: /sk-[A-Za-z0-9]{32,}/
          - pattern: /(?i)AWS_SECRET_ACCESS_KEY\s*=\s*[A-Za-z0-9\/\+=]{40}/
          - pattern: /(?i)AWS_ACCESS_KEY_ID\s*=\s*AKIA[0-9A-Z]{16}/
          - pattern: /(?i)PASSWORD\s*=\s*[^\\s]+/
          - pattern: /(?i)SECRET\s*=\s*[^\\s]+/

  # CI hygiene: disallow sleep in tests
  - id: local.ci.no-sleep-in-tests
    languages: [javascript, typescript, python, rust]
    message: Avoid sleep in tests (flaky/slow CI)
    severity: WARNING
    paths:
      include: ["**/*test*.*", "**/tests/**"]
    patterns:
      - pattern-either:
          - pattern: sleep(...)
          - pattern: asyncio.sleep(...)
          - pattern: setTimeout(...)
    metadata:
      category: ci

  # Enforce safe fs open in Rust (no unwrap on File::open)
  - id: local.rust.no-file-open-unwrap
    languages: [rust]
    message: Avoid unwrap() on File::open to prevent crashes
    severity: WARNING
    patterns:
      - pattern: File::open(...).unwrap()

  # JS/TS: forbid dynamic import with template literal without prefix (semgrep-friendly)
  - id: local.js.dynamic-import-template
    languages: [javascript, typescript]
    message: Dynamic import with template literal can bypass graph analysis
    severity: WARNING
    patterns:
      - pattern: import(`...`)
      - pattern-not: import(`./${...}`)

  # JS/TS: block eval/new Function
  - id: local.js.no-eval
    languages: [javascript, typescript]
    message: Avoid eval/new Function for safety and analyzability
    severity: ERROR
    patterns:
      - pattern-either:
          - pattern: eval(...)
          - pattern: new Function(...)

  # Python: forbid __import__ without literal
  - id: local.py.dynamic-import-literal
    languages: [python]
    message: __import__ without literal makes graph incomplete
    severity: WARNING
    patterns:
      - pattern: __import__($X)
      - pattern-not: __import__("...")

  # Python: discourage shell=True in subprocess
  - id: local.py.subprocess-shell
    languages: [python]
    message: Avoid subprocess with shell=True (command injection risk)
    severity: WARNING
    pattern-either:
      - patterns:
          - pattern: subprocess.$FUNC(..., shell=True, ...)
          - metavariable-regex:
              metavariable: $FUNC
              regex: "(run|Popen|call|check_call|check_output)"

  # Rust: avoid unwrap in command handlers (generic guard)
  - id: local.rust.no-unwrap
    languages: [rust]
    message: Avoid unwrap(); use ? or expect with context
    severity: WARNING
    patterns:
      - pattern: $X.unwrap()

  # Bash: disallow curl|bash style installers
  - id: local.bash.no-curl-pipe-sh
    languages: [bash]
    message: Avoid piping curl/wget output to shell
    severity: ERROR
    patterns:
      - pattern-either:
          - pattern: curl ... | sh
          - pattern: wget ... | sh
