#!/usr/bin/env bash
set -euo pipefail

# Update Homebrew tap formula for loctree.
#
# This helper prints a curlable formula body. It does not push commits.
# Intended workflow: run build-and-publish.sh; then copy the printed formula into the tap repo.
#
# Usage: tools/release/update-tap.sh <version> <config.json>

VERSION=${1:?"version tag (e.g. v0.8.9) required"}
CONFIG=${2:?"config json path required"}

ROOT=$(cd "$(dirname "$0")/../.." && pwd)

artifact_name=$(jq -r '.artifact_name' "$CONFIG")
repo=$(jq -r '.repo' "$CONFIG")
tap=$(jq -r '.tap // empty' "$CONFIG")
targets=$(jq -r '.targets[]' "$CONFIG")

release_dir="$ROOT/tmp/release/$VERSION"
if [[ ! -d "$release_dir" ]]; then
  echo "release artifacts missing: $release_dir" >&2
  exit 1
fi

sha256_file() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
    return
  fi
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$file" | awk '{print $1}'
    return
  fi
  if command -v openssl >/dev/null 2>&1; then
    # openssl prints: "SHA2-256(<file>)= <hash>"
    openssl dgst -sha256 "$file" | awk '{print $2}'
    return
  fi
  echo "sha256 tool not found (need sha256sum, shasum, or openssl)" >&2
  exit 1
}

darwin_arm_url=""
darwin_arm_sha=""
darwin_intel_url=""
darwin_intel_sha=""
linux_arm_url=""
linux_arm_sha=""
linux_intel_url=""
linux_intel_sha=""
first_url=""
first_sha=""

for target in $targets; do
  tarball="$release_dir/${artifact_name}-${target}.tar.gz"
  if [[ ! -f "$tarball" ]]; then
    echo "missing tarball $tarball" >&2
    exit 1
  fi

  sha=$(sha256_file "$tarball")
  url="https://github.com/${repo}/releases/download/${VERSION}/${artifact_name}-${target}.tar.gz"

  if [[ -z "$first_url" ]]; then
    first_url="$url"
    first_sha="$sha"
  fi

  if [[ "$target" == *"apple-darwin"* ]]; then
    if [[ "$target" == aarch64* ]]; then
      darwin_arm_url="$url"
      darwin_arm_sha="$sha"
    else
      darwin_intel_url="$url"
      darwin_intel_sha="$sha"
    fi
    continue
  fi

  if [[ "$target" == *"unknown-linux-gnu"* ]]; then
    if [[ "$target" == aarch64* ]]; then
      linux_arm_url="$url"
      linux_arm_sha="$sha"
    else
      linux_intel_url="$url"
      linux_intel_sha="$sha"
    fi
    continue
  fi
done

cat <<EOF
# Generated by tools/release/update-tap.sh
class Loctree < Formula
  desc "LOC-aware tree (Rust)"
  homepage "https://github.com/${repo}"
  version "${VERSION}"
EOF

if [[ -n "$darwin_arm_url" || -n "$darwin_intel_url" ]]; then
  echo "  on_macos do"
  if [[ -n "$darwin_arm_url" ]]; then
    cat <<EOF
    on_arm do
      url "${darwin_arm_url}"
      sha256 "${darwin_arm_sha}"
    end
EOF
  fi
  if [[ -n "$darwin_intel_url" ]]; then
    cat <<EOF
    on_intel do
      url "${darwin_intel_url}"
      sha256 "${darwin_intel_sha}"
    end
EOF
  fi
  echo "  end"
fi

if [[ -n "$linux_arm_url" || -n "$linux_intel_url" ]]; then
  echo "  on_linux do"
  if [[ -n "$linux_arm_url" ]]; then
    cat <<EOF
    on_arm do
      url "${linux_arm_url}"
      sha256 "${linux_arm_sha}"
    end
EOF
  fi
  if [[ -n "$linux_intel_url" ]]; then
    cat <<EOF
    on_intel do
      url "${linux_intel_url}"
      sha256 "${linux_intel_sha}"
    end
EOF
  fi
  echo "  end"
fi

if [[ -z "$darwin_arm_url" && -z "$darwin_intel_url" && -z "$linux_arm_url" && -z "$linux_intel_url" ]]; then
  cat <<EOF
  url "${first_url}"
  sha256 "${first_sha}"
EOF
fi

cat <<'EOF'

  def install
    bin.install "loctree"
  end

  test do
    output = shell_output("#{bin}/loctree --json")
    assert_match "entries", output
  end
end
EOF

if [[ -n "$tap" ]]; then
  echo ""
  echo "# TODO: commit this formula to tap repo: $tap"
  echo ""
fi

