#!/usr/bin/env python3
"""Update Homebrew tap formula for loctree.

This is a lightweight helper that prints the curlable formula body. It does not push.
Intended workflow: run build-and-publish.sh; then copy the printed formula into the tap repo
(Loctree/homebrew-loctree) or wire a GitHub Action to commit it.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, List


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> None:
    if len(sys.argv) < 3:
        print("usage: update-tap.py <version> <config.json>", file=sys.stderr)
        sys.exit(1)
    version = sys.argv[1]
    config_path = Path(sys.argv[2])
    cfg = json.loads(config_path.read_text())
    artifact_name: str = cfg["artifact_name"]
    repo: str = cfg["repo"]
    targets: List[str] = cfg["targets"]
    tap: str = cfg.get("tap", "")
    root = Path(__file__).resolve().parents[2]
    release_dir = root / "tmp" / "release" / version
    if not release_dir.is_dir():
        raise SystemExit(f"release artifacts missing: {release_dir}")

    assets: Dict[str, str] = {}
    for target in targets:
        tarball = release_dir / f"{artifact_name}-{target}.tar.gz"
        if not tarball.exists():
            raise SystemExit(f"missing tarball {tarball}")
        assets[target] = sha256(tarball)

    class Formula:
        def __init__(self, url: str, sha: str, target: str) -> None:
            self.url = url
            self.sha = sha
            self.target = target

    formulas: List[Formula] = []
    for target, digest in assets.items():
        url = f"https://github.com/{repo}/releases/download/{version}/{artifact_name}-{target}.tar.gz"
        formulas.append(Formula(url, digest, target))

    # Simple formula that assumes universal binary? We'll emit per-arch blocks for macOS; linux bottle left manual.
    mac_formulas = [f for f in formulas if "apple-darwin" in f.target]
    linux_formulas = [f for f in formulas if "unknown-linux-gnu" in f.target]

    print("""# Generated by tools/release/update-tap.py
class Loctree < Formula
  desc "LOC-aware tree (Rust)"
  homepage "https://github.com/{repo}"
  version "{version}"
""".format(repo=repo, version=version))

    if mac_formulas:
        for f in mac_formulas:
            on_arch = "arm64" if "aarch64" in f.target else "intel"
            print(f"  on_{on_arch} do")
            print(f"    url \"{f.url}\"")
            print(f"    sha256 \"{f.sha}\"")
            print("  end")
    else:
        first = formulas[0]
        print(f"  url \"{first.url}\"")
        print(f"  sha256 \"{first.sha}\"")

    print(
        "  def install\n    bin.install \"loctree\"\n  end\n\n  test do\n    output = shell_output(\"#{bin}/loctree --json\")\n    assert_match \"entries\", output\n  end\nend")

    if tap:
        print(f"\n# TODO: commit this formula to tap repo: {tap}\n")


if __name__ == "__main__":
    main()
