//! Root document component - the complete HTML page

use leptos::prelude::*;
use crate::styles::{REPORT_CSS, CSP};
use crate::types::ReportSection;
use crate::JsAssets;
use super::{AiSummaryPanel, ReportSectionView};

/// The complete HTML document for the report
#[component]
pub fn ReportDocument(
    sections: Vec<ReportSection>,
    js_assets: JsAssets,
) -> impl IntoView {
    let section_count = sections.len();

    view! {
        <html>
            <head>
                <meta charset="UTF-8" />
                <meta http-equiv="Content-Security-Policy" content=CSP />
                <title>"loctree import/export report"</title>
                <style>{REPORT_CSS}</style>
            </head>
            <body>
                <div class="report-page">
                    <header class="report-nav">
                        <div class="container report-nav-inner">
                            <div class="report-nav-title">"loctree report"</div>
                            <div class="report-nav-meta">
                                {move || {
                                    if section_count == 0 {
                                        "no sections".to_string()
                                    } else if section_count == 1 {
                                        "1 section".to_string()
                                    } else {
                                        format!("{} sections", section_count)
                                    }
                                }}
                            </div>
                        </div>
                    </header>

                    <div class="container report-layout">
                        <aside class="report-sidebar">
                            <h2>"Sections"</h2>
                            <ul>
                                {sections.iter().enumerate().map(|(idx, section)| {
                                    let id = format!("section-{}", idx);
                                    let label = section.root.clone();
                                    view! {
                                        <li>
                                            <a href=format!("#{}", id)>{label}</a>
                                        </li>
                                    }
                                }).collect::<Vec<_>>()}
                            </ul>
                        </aside>

                        <main class="report-main">
                            <header class="report-header">
                                <h1>"loctree import/export analysis"</h1>
                                <p class="report-subtitle">"Static analysis snapshot rendered with Leptos SSR."</p>
                            </header>

                            <AiSummaryPanel sections=sections.clone() />

                            {sections.into_iter().enumerate().map(|(idx, section)| {
                                let id = format!("section-{}", idx);
                                view! {
                                    <section id=id class="report-section-anchor">
                                        <ReportSectionView section=section.clone() />
                                    </section>
                                }
                            }).collect::<Vec<_>>()}
                        </main>
                    </div>

                    <footer class="report-footer">
                        <div class="container">
                            <span>"Generated by loctree — fast, language-aware codebase analyzer."</span>
                        </div>
                    </footer>

                    <GraphScripts js_assets=js_assets />
                </div>
            </body>
        </html>
    }
}

/// JavaScript for graph initialization
#[component]
fn GraphScripts(js_assets: JsAssets) -> impl IntoView {
    // Only render script tags if paths are provided
    let has_assets = !js_assets.cytoscape_path.is_empty();

    view! {
        {has_assets.then(|| view! {
            <script src=js_assets.cytoscape_path.clone()></script>
            <script src=js_assets.dagre_path.clone()></script>
            <script src=js_assets.cytoscape_dagre_path.clone()></script>
            <script src=js_assets.cytoscape_cose_bilkent_path.clone()></script>
            <script>{include_str!("../graph_bootstrap.js")}</script>
            <script>{TAB_SCRIPT}</script>
        })}
    }
}

/// Tab switching script (vanilla JS)
const TAB_SCRIPT: &str = r#"
(() => {
  document.querySelectorAll(".tab-bar").forEach((bar) => {
    const scope = bar.dataset.tabScope || "";
    bar.querySelectorAll("button").forEach((btn) => {
      btn.addEventListener("click", () => {
        bar.querySelectorAll("button").forEach((b) => b.classList.remove("active"));
        btn.classList.add("active");
        const target = btn.dataset.tab;
        document.querySelectorAll(`[data-tab-panel^="${scope}-"]`).forEach((panel) => {
          panel.classList.toggle("active", panel.dataset.tabPanel === target);
        });
      });
    });
  });
})();
"#;
