# Loctree CI/CD Workflow v2.0 - Artifact-First Architecture
# Compatible with loctree 0.8.0+
#
# Vibecrafted with AI Agents by VetCoders (c)2025 The Loctree Team
# Co-Authored-By: Maciej <void@div0.space> & Klaudiusz <the1st@whoai.am>

name: Loctree Code Quality

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - develop

env:
  # Health score threshold (0-100)
  HEALTH_THRESHOLD: 50
  # Fail on findings (true/false)
  FAIL_ON_FINDINGS: false
  # Maximum dead exports allowed (0 = any is failure)
  MAX_DEAD_EXPORTS: 10
  # Maximum cycles allowed
  MAX_CYCLES: 0

jobs:
  loctree-analysis:
    name: Structural Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Loctree
        run: |
          # Install from crates.io (recommended)
          cargo install loctree --locked

          # Verify installation
          loct --version || {
            echo "::error::loct command not found after installation"
            exit 1
          }

      - name: Run Loctree Scan
        id: scan
        run: |
          echo "## 🌳 Loctree Analysis Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Run full scan - generates .loctree/ artifacts
          loct auto --json > /tmp/scan-output.json 2>&1 || true

          # Extract health score from agent.json
          if [ -f .loctree/agent.json ]; then
            HEALTH=$(jq -r '.summary.health_score // 0' .loctree/agent.json)
            FILES=$(jq -r '.summary.files_analyzed // 0' .loctree/agent.json)
            LOC=$(jq -r '.summary.total_loc // 0' .loctree/agent.json)
            DEAD=$(jq -r '.summary.dead_exports // 0' .loctree/agent.json)
            CYCLES=$(jq -r '.summary.circular_imports // 0' .loctree/agent.json)
            TWINS=$(jq -r '.summary.twins_same_language // 0' .loctree/agent.json)

            echo "health=$HEALTH" >> $GITHUB_OUTPUT
            echo "files=$FILES" >> $GITHUB_OUTPUT
            echo "dead=$DEAD" >> $GITHUB_OUTPUT
            echo "cycles=$CYCLES" >> $GITHUB_OUTPUT

            # Build summary
            echo "### Health Score: ${HEALTH}/100" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
            echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
            echo "| Files analyzed | $FILES |" >> $GITHUB_STEP_SUMMARY
            echo "| Total LOC | $LOC |" >> $GITHUB_STEP_SUMMARY
            echo "| Dead exports | $DEAD |" >> $GITHUB_STEP_SUMMARY
            echo "| Circular imports | $CYCLES |" >> $GITHUB_STEP_SUMMARY
            echo "| Twins | $TWINS |" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY

            # Priority message if present
            PRIORITY=$(jq -r '.summary.priority // empty' .loctree/agent.json)
            if [ -n "$PRIORITY" ]; then
              echo "> **Priority**: $PRIORITY" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "::warning::No agent.json found - scan may have failed"
            echo "health=0" >> $GITHUB_OUTPUT
            echo "files=0" >> $GITHUB_OUTPUT
            echo "dead=0" >> $GITHUB_OUTPUT
            echo "cycles=0" >> $GITHUB_OUTPUT
          fi

      - name: Check Health Threshold
        if: steps.scan.outputs.health != ''
        run: |
          HEALTH=${{ steps.scan.outputs.health }}
          if [ "$HEALTH" -lt "${{ env.HEALTH_THRESHOLD }}" ]; then
            echo "::error::Health score $HEALTH is below threshold (${{ env.HEALTH_THRESHOLD }})"
            exit 1
          fi

      - name: Check Dead Exports
        if: env.MAX_DEAD_EXPORTS != '' && steps.scan.outputs.dead != ''
        run: |
          DEAD=${{ steps.scan.outputs.dead }}
          MAX=${{ env.MAX_DEAD_EXPORTS }}
          if [ "$DEAD" -gt "$MAX" ]; then
            echo "::warning::Found $DEAD dead exports (threshold: $MAX)"

            # Show top dead exports in summary
            echo "### Dead Exports" >> $GITHUB_STEP_SUMMARY
            loct dead --confidence high --top 10 2>/dev/null >> $GITHUB_STEP_SUMMARY || true
          fi

      - name: Check Circular Imports
        if: env.MAX_CYCLES != '' && steps.scan.outputs.cycles != ''
        run: |
          CYCLES=${{ steps.scan.outputs.cycles }}
          MAX=${{ env.MAX_CYCLES }}
          if [ "$CYCLES" -gt "$MAX" ]; then
            echo "::error::Found $CYCLES circular imports (max allowed: $MAX)"

            # Show cycles in summary
            echo "### Circular Imports" >> $GITHUB_STEP_SUMMARY
            loct cycles 2>/dev/null >> $GITHUB_STEP_SUMMARY || true

            if [ "${{ env.FAIL_ON_FINDINGS }}" = "true" ]; then
              exit 1
            fi
          fi

      - name: Run Structural Lint
        if: env.FAIL_ON_FINDINGS == 'true'
        run: |
          # Run lint with fail flag
          loct lint --fail 2>&1 || {
            echo "::error::Structural lint failed"
            exit 1
          }

      - name: Generate SARIF Report
        if: always()
        run: |
          # Generate SARIF for GitHub Code Scanning
          loct lint --sarif > loctree.sarif 2>/dev/null || true

          if [ -f loctree.sarif ] && [ -s loctree.sarif ]; then
            echo "SARIF report generated"
          fi

      - name: Upload SARIF to GitHub
        if: always() && hashFiles('loctree.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: loctree.sarif
          category: loctree
        continue-on-error: true

      - name: Upload Loctree Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: loctree-analysis
          path: |
            .loctree/
            loctree.sarif
          if-no-files-found: ignore
          retention-days: 30

  # Optional: PR Comment with findings
  pr-comment:
    name: PR Comment
    runs-on: ubuntu-latest
    needs: loctree-analysis
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: loctree-analysis
          path: .loctree-artifacts
        continue-on-error: true

      - name: Post PR Comment
        if: hashFiles('.loctree-artifacts/.loctree/agent.json') != ''
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            try {
              const agent = JSON.parse(fs.readFileSync('.loctree-artifacts/.loctree/agent.json', 'utf8'));
              const summary = agent.summary || {};

              const health = summary.health_score || 0;
              const healthEmoji = health >= 80 ? '🟢' : health >= 50 ? '🟡' : '🔴';

              const body = `## 🌳 Loctree Analysis

${healthEmoji} **Health Score: ${health}/100**

| Metric | Value |
|--------|-------|
| Files | ${summary.files_analyzed || 0} |
| LOC | ${summary.total_loc || 0} |
| Dead exports | ${summary.dead_exports || 0} |
| Cycles | ${summary.circular_imports || 0} |
| Twins | ${summary.twins_same_language || 0} |

${summary.priority ? `> **Priority**: ${summary.priority}` : ''}

<sub>Generated by [Loctree](https://github.com/Loctree/Loctree) • Vibecrafted with AI Agents by VetCoders (c)2025 The Loctree Team</sub>`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            } catch (e) {
              console.log('Could not post comment:', e.message);
            }
